# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kNkpLPfJzUqtA4l3smAgbA8Zl7XrDhFO
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import shutil
import random
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5

!pip install -r requirements.txt

!wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5x.pt

!python train.py --img 640 --batch 8 --epochs 20 --data /content/yolov5/data/dataset.yaml --weights /content/yolov5/yolov5x.pt --nosave --cache

!zip -r /content/yolov5.zip /content/yolov5

!python detect.py --source /content/drive/MyDrive/img169.png  --weights /content/yolov5/runs/train/exp2/weights/best.pt

